# -*- coding: utf-8 -*-
{
    'name': 'Payroll 3C',
    'summary': 'Payroll 3C – scaffold with roles, menus, sequences',
    'version': '17.0.1.0.0',
    'author': '3C',
    'website': '',
    'category': 'Human Resources/payroll',
    'license': 'LGPL-3',
    'depends': ['base', 'employee_3c', 'project_3c', 'timesheet_3c'],  # depends on Project 3C for task/tag models
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # Actions first to satisfy menu references
        'views/actions.xml',
    'data/sequence.xml',
    'data/kpi_default_quality.xml',
    'data/vn_params_data.xml',
    'data/rule_structure_data.xml',
    'data/rule_updates.xml',
    'data/payslip_server_actions.xml',
    'data/refresh_variable_catalog_action.xml',
    'data/delete_actions.xml',
        'views/wizard_views.xml',
    'views/salary_profile_views.xml',
        'views/variable_views.xml',
        'views/template_views.xml',
        'views/sheet_views.xml',
        'views/rule_views.xml',
        'views/params_views.xml',
    'views/kpi_sheet_views.xml',
    'views/kpi_record_views.xml',
        'views/kpi_group_views.xml',
        'views/kpi_label_views.xml',
        'views/kpi_quality_views.xml',
        'views/kpi_period_views.xml',
        'views/payslip_views.xml',
        'views/kpi_adjust_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'payroll_3c/static/src/scss/payroll_template.scss',
            'payroll_3c/static/src/scss/payroll_template_fix.scss',
        ],
    },
    'installable': True,
    'application': True,
    'images': ['static/description/icon.svg'],
}
